[package]
name = "simple_ctv"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
bitcoin = "0.32.4"
bitcoincore-rpc = "0.19.0"

[features]
default = ["regtest"]
signet = []
regtest = []
