[package]
name = "simple_ctv"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
bitcoin = "0.32.4"
anyhow = "1.0.90"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bitcoincore-rpc = "0.19.0"

[features]
# wen op_ctv mainnet
signet = []
